from aiogram.dispatcher.filters.state import State, StatesGroup
class Form(StatesGroup):
    OtaState = State()
    BolaState = State()
    GetMenu = State()
    GetMenu2 = State()
    GetMenu3 = State()
    FileState = State()
    MessageId = State()
    MenuNameState = State()
    channel = State()
    channel_add2 = State()
    ChannelRemove = State()
    OneUser = State()
    OneUser2 = State()
    ManyUser = State()
    ManyUser2 = State()
    AllUsers = State()
    AdminAdd = State()
    AdminRemove = State()
    MenuRemove = State()
    ClearState = State()
    IdChange = State()
    IdAdd = State()
    IdRemove = State()

    LangChange = State()
    LangChange1 = State()